PermissionManagement.Web/Controllers/UserSetupController.cs
using DataTables.Mvc;
using PermissionManagement.Model;
using PermissionManagement.Repository;
using PermissionManagement.Services;
using PermissionManagement.Utility;
using PermissionManagement.Validation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PermissionManagement.Web
{
    public class UserSetupController : BaseController
    {
        #region Properties and Variables
        private ISecurityService _securityService;
        private ICacheService _cacheService;
        private IFinacleRepository _flexCubeRepository;
        #endregion

        public UserSetupController(ISecurityService securityService, ICacheService cacheService, IFinacleRepository finacleRepository)
        {
            _securityService = securityService;
            _flexCubeRepository = finacleRepository;
            _cacheService = cacheService;
        }

        [AuditFilter(AuditLogLevel.LevelThree)]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.View)]
        public ActionResult Index()
        {
            return RedirectToAction("ListUser");
            //var userList = new UserListingResponse();
            //return View("ListUser", userList);
        }

        #region Roles Action Results

        #region Create Role
        [AuditFilter(AuditLogLevel.LevelThree)]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.Create)]
        public ActionResult CreateRole()
        {
            var list = _securityService.GetModuleAccessList().ToList();
            var roleToCreate = new RoleViewModel() { CurrentRole = new Role(), ModuleAccessList = list };
            return View(roleToCreate);
        }

        [AuditFilter()]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.Create)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRole(RoleViewModel model)
        {
            {
                ValidationStateDictionary states = new ValidationStateDictionary();
                _securityService.AddRole(model, ref states);
                if (!states.IsValid)
                {
                    var errorList = ValidationHelper.BuildModelErrorList(states);
                    Danger(string.Format("{0}<br />{1}", Constants.Messages.ErrorNotice, errorList), true);
                    ModelState.AddModelErrors(states);
                    SetAuditInfo(Helper.StripHtml(errorList, true), string.Empty);
                    return View(model);
                }
                else
                {
                    Success(Constants.Messages.AddSuccessful, true);
                    return RedirectToAction("EditRole", new { id = model.CurrentRole.RoleId });
                }
            }
        }

        #endregion

        #region Edit Roles
        [AuditFilter(AuditLogLevel.LevelThree)]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.View)]
        public ActionResult EditRole(Guid id)
        {
            var roleToEdit = _securityService.GetRole(id);
            return View(roleToEdit);
        }
        [AuditFilter()]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.Edit)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditRole(RoleViewModel model)
        {
            {
                ValidationStateDictionary states = new ValidationStateDictionary();
                var updated = _securityService.EditRole(model, ref states);
                if (!states.IsValid)
                {
                    var errorList = ValidationHelper.BuildModelErrorList(states);
                    Danger(string.Format("{0}<br />{1}", Constants.Messages.ErrorNotice, errorList), true);
                    ModelState.AddModelErrors(states);
                    SetAuditInfo(Helper.StripHtml(errorList, true), string.Empty);
                    return View(model);
                }
                else
                {
                    if (updated == 0) { Warning(Constants.Messages.ConcurrencyError, true); }
                    else { Success(Constants.Messages.SaveSuccessful, true); }
                    return RedirectToAction("EditRole", new { id = model.CurrentRole.RoleId });
                }
            }
        }
        #endregion

        #region Other Action Results
        [AuditFilter(AuditLogLevel.LevelThree)]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.View)]
        public ActionResult ListRole()
        {
            var roleList = _securityService.GetRoleList();
            return View(roleList);
        }
        [SecurityAccess]
        [CompressFilter]
        [HttpPost]
        public void ExportExcel(string searchKey)
        {
            IEnumerable<Role> roleList = null;
            roleList = string.IsNullOrEmpty(searchKey) ? _securityService.GetRoleList() : _securityService.GetRoleList().Where(c => c.RoleName.ToString() == searchKey || c.Description == searchKey);
            //IEnumerable<ExpiredUserListingDto> excelData = _reportService.GetExcelReportForUsers(uiInputSearchParam, fromDate, toDate, reportType);
            new Export().ToFile(roleList, Response, "RolesList_Report");
        }
        //ExportUsersToExcel

        [SecurityAccess]
        [CompressFilter]
        [HttpPost]
        public void ExportUsersToExcel(FormCollection formCollection)
        {
            List<ExportDto> usersList = null;
            usersList = _securityService.GetUserListForExcel(formCollection["searchKey"]);
            new Export().ToFile(usersList, Response, "UsersList_Report");
        }

        [SecurityAccess]
        [CompressFilter]
        [HttpPost]
        public void ExportUsersToWord(FormCollection formCollection)
        {
            List<ExportDto> usersList = null;
            usersList = _securityService.GetUserListForExcel(formCollection["searchKey"]);
            new Export().ToFile(usersList, Response, "UsersList_Report",EXPORTTYPE.WORD);
        }

        [AuditFilter(AuditLogLevel.LevelThree)]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.Delete)]
        public ActionResult DeleteRole(Guid id)
        {
            ValidationStateDictionary states = new ValidationStateDictionary();
            _securityService.DeleteRole(id, ref states);
            if (!states.IsValid)
            {
                var errorList = ValidationHelper.BuildModelErrorList(states);
                Danger(string.Format("{0}<br />{1}", Constants.Messages.ErrorNotice, errorList), true);
                return RedirectToAction("ListRole");
            }
            else
            {
                Success(Constants.Messages.DeleteSuccessful, true);
                return RedirectToAction("ListRole");
            }
        }

        #endregion

        #endregion

        #region User Action Results

        #region Create User
        [AuditFilter(AuditLogLevel.LevelThree)]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.Create)]
        public ActionResult CreateUser()
        {
            var userToCreate = new User() { UserRole = new Role() { RoleId = Guid.Empty } };
            userToCreate.CreationDate = Helper.GetLocalDate();
            userToCreate.LastLogInDate = Helper.GetLocalDate();
            userToCreate.LastActivityDate = Helper.GetLocalDate();
            return View(userToCreate);
        }

        [AuditFilter()]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.Create)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUser(User model)
        {
            ValidationStateDictionary states = new ValidationStateDictionary();
            model.UserRole = new Role() { RoleId = model.RoleId, RoleName = (from r in _securityService.GetRoleList() where r.RoleId == model.RoleId select r.RoleName).FirstOrDefault() };
            model.InitiatedBy = ControllerContext.RequestContext.HttpContext.User.Identity.Name;
            if (model.AccountType == Constants.AccountType.LocalFinacle || model.AccountType == Constants.AccountType.ADLocal)
            {
                var flexcubeRecord = _flexCubeRepository.GetUserRoleFromFlexcube(model.Username);
                if (flexcubeRecord != null) { model.BranchID = flexcubeRecord.BranchCode; }
            }
            
            if (model.AccountType == Constants.AccountType.ADLocal && !string.IsNullOrEmpty(model.Username))
            {
                if (!Access.IsUserInAD(model.Username))
                {
                    var errorMsg = "The user does not exist on AD or AD service could not be reached.";
                    Danger(errorMsg, true);
                    SetAuditInfo(errorMsg, string.Empty);
                    return View(model);
                }
            }
            _securityService.AddUser(model, ref states);
            if (!states.IsValid)
            {
                model.UserRole = new Role() { RoleId = model.RoleId };
                ModelState.AddModelErrors(states);
                var errorList = ValidationHelper.BuildModelErrorList(states);
                SetAuditInfo(Helper.StripHtml(errorList, true), string.Empty);
                return View(model);
            }
            else
            {
                Success(Constants.Messages.AddSuccessful, true);
                return RedirectToAction("EditUser", new { id = model.Username });
            }
        }

        #endregion

        #region Edit User
        [AuditFilter(AuditLogLevel.LevelThree)]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.View)]
        public ActionResult EditUser(string id)
        {
            //var userToEdit = _securityService.GetUserByUsername(id);
            var userToEdit = _securityService.GetUser(id);

            if (userToEdit != null)
            {

PermissionManagement.Web/Views/UserSetup/ApproveUser.cshtml
@using PermissionManagement.Utility;
@model PermissionManagement.Model.User
@{
    ViewBag.Title = "Approve User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section MainContent {

    <div class="row">
        <div class="form-horizontal col-md-12 col-xs-12 col-xs-offset-0">
            <div class="col-md-12 col-xs-12 col-sm-12 align-text-bottom page-head-line">
                Approver User
            </div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Username)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Username)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Initial)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Initial)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FirstName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LastName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Email)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.UserRole.RoleName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UserRole.RoleName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsLockedOut)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsLockedOut)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Telephone)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Telephone)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CreationDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CreationDate)

                <dt>
                    @Html.DisplayNameFor(model => model.AccountType)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AccountType)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.BranchID)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.BranchID)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ApprovalStatus)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ApprovalStatus)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.InitiatedBy)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.InitiatedBy)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ApprovedBy)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ApprovedBy)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.StaffPosition)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.StaffPosition)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsDormented)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsDormented)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.AccountExpiryDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AccountExpiryDate)
                </dd>
            </dl>
        </div>
        @using (Html.BeginForm("ApproveUser", "UserSetup", FormMethod.Post, new { id = "approveUserForm" }))
        {
        <div id="approveUserDetailDiv">
        @Html.AntiForgeryToken()
        <div class="col-md-12 col-xs-12">
            <div class="form-group">
                <div class="col-md-4">
                    <input type="submit" value="Approve" name="action:ApproveUser" class="form-control btn-primary" />
                </div>
                <div class="col-md-4">
                    <input type="submit" value="Reject" name="action:RejectUser" class="form-control btn-primary" />
                </div>
                <div class="col-md-4">
                    <input type="submit" value="Reject for Correction" onclick="GetComment(this); return false;" class="form-control btn-primary"/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-8 col-xs-12 col-xs-offset-0">
                <div id="dialog4" tabindex="-1" role="dialog" aria-labelledby="dialog4Label" aria-hidden="true" class="modal fade">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h4 class="modal-title" id="dialog4Label">Enter Comment</h4>
                            </div>
                            <div class="modal-body">
                                <p>Please enter your comment for the approval or rejection.</p>
                                <div class="row">
                                    <div class="col-md-10 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label class="control-label col-md-2" for="ApproverComment">Approver Comment</label>
                                            <div class="col-md-10">
                                                <input class="form-control input-sm text-box single-line" id="ApproverComment" name="ApproverComment" type="text" value="" />
                                                <span class="field-validation-valid text-danger" data-valmsg-for="ApproverComment" data-valmsg-replace="true"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <input type="submit" value="Close" class="btn btn-primary" data-dismiss="modal" />
                                <input type="submit" value="Submit" onclick="SubmitChange(this);" class="btn btn-primary" data-dismiss="modal"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @Html.Hidden("Username", Model.Username)
    </div>
     }
    </div>
}
@section scripts {
    <script type="text/javascript">

        function GetComment(btn) {

            $('#dialog4').modal('show');
        }

        @*$("#rejectChange").click(function () { $('#dialog4').modal('show');});*@

        function SubmitChange(btn) {

            
            $obj = $("#action:RejectForCorrectionUser");
            if (!jQuery.contains(document, $obj[0])) {
                $('#approveUserForm').append($('<input id="action:RejectForCorrectionUser" name="action:RejectForCorrectionUser" type="hidden" value="Reject for Correction"/>'));
            }

            var rootUrl = "@Helper.GetRootURL()";
		    var id = "@ViewBag.ModelId";
            var postUrl = rootUrl + "/UserSetup/ApproveUser/" + id; 
            var redirectUrl = rootUrl + "/UserSetup/ListUser";
            $.ajax({
                type: "POST",
                url: postUrl,
                data: $('#approveUserForm').serialize(),
                datatype: "html",
                success: function (data) { 
                    window.location.href = redirectUrl;
                    return;
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    if (jqXHR.status === 401) {
                        window.location.href = jqXHR.Data.LogOnUrl;
                        return;
                    }
                    else {
                        BootstrapDialog.alert(jqXHR.responseText);
                    }
                }
            });
        }
    </script>
}

PermissionManagement.Web/Views/UserSetup/CreateRole.cshtml
@using PermissionManagement.Utility;
@model PermissionManagement.Model.RoleViewModel
@{
    ViewBag.Title = "Create Role";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section MainContent {
<div class="row">
	<div class="col-md-12 col-xs-12 col-sm-12 align-text-bottom page-head-line">
		Create Role |
		@*@Html.ActionLink("Back to List", "ListRole")*@
		<a href="@Url.Action("ListRole", "UserSetup")" class="btn btn-link btn-sm text-capitalize">
			<i class="fa fa-arrow-left" aria-hidden="true"></i>
			Back to List
		</a>
	</div>
</div>
<div class="row">
	@using (Html.BeginForm("CreateRole", "UserSetup",FormMethod.Post, new { @class = "form-horizontal col-md-10 col-xs-12 col-sm-12 col-md-offset-1" }))
	{
		@Html.AntiForgeryToken()
		<span >
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			@{Html.RenderPartial("RoleEditor");}
		</span>
	}
</div>
}
@section scripts {
    <script type="text/javascript">

    function validateVerifyAccess(sender) {

            ctrl = sender;
            var verifyCheck = document.getElementById(ctrl.id);
            if (verifyCheck.checked == true) {  // if verify access is checked, uncheck all others, except view access
                var makeOrCheck = document.getElementById(ctrl.id.replace("VerifyAccess", "MakeOrCheckAccess"));
                makeOrCheck.checked = false;
                var createCheck = document.getElementById(ctrl.id.replace("VerifyAccess", "CreateAccess"));
                createCheck.checked = false;
                var editCheck = document.getElementById(ctrl.id.replace("VerifyAccess", "EditAccess"));
                editCheck.checked = false;
                var deleteCheck = document.getElementById(ctrl.id.replace("VerifyAccess", "DeleteAccess"));
                deleteCheck.checked = false;
                var viewCheck = document.getElementById(ctrl.id.replace("VerifyAccess", "ViewAccess"));
                viewCheck.checked = true;
            }
        }

    function validateMakeOrCheckAccess(sender) {

            ctrl = sender;
            var MakeOrCheck = document.getElementById(ctrl.id);
            if (MakeOrCheck.checked == true) {  // if MakeOrCheck access is checked, uncheck verify and check all others
                var verifyCheck = document.getElementById(ctrl.id.replace("MakeOrCheckAccess", "VerifyAccess"));
                verifyCheck.checked = false;
                var createCheck = document.getElementById(ctrl.id.replace("MakeOrCheckAccess", "CreateAccess"));
                createCheck.checked = true;
                var editCheck = document.getElementById(ctrl.id.replace("MakeOrCheckAccess", "EditAccess"));
                editCheck.checked = true;
                var deleteCheck = document.getElementById(ctrl.id.replace("MakeOrCheckAccess", "DeleteAccess"));
                deleteCheck.checked = true;
                var viewCheck = document.getElementById(ctrl.id.replace("MakeOrCheckAccess", "ViewAccess"));
                viewCheck.checked = true;
            }
        }

    function validateViewAccess(sender) {

        ctrl = sender;
        var viewCheck = document.getElementById(ctrl.id);
        if (viewCheck.checked == false) {  // if view access is unchecked, uncheck all others.
            var createCheck = document.getElementById(ctrl.id.replace("ViewAccess", "CreateAccess"));
            createCheck.checked = false;
            var editCheck = document.getElementById(ctrl.id.replace("ViewAccess", "EditAccess"));
            editCheck.checked = false;
            var deleteCheck = document.getElementById(ctrl.id.replace("ViewAccess", "DeleteAccess"));
            deleteCheck.checked = false;
            var verifyCheck = document.getElementById(ctrl.id.replace("ViewAccess", "VerifyAccess"));
            verifyCheck.checked = false;
            var makeOrCheck = document.getElementById(ctrl.id.replace("ViewAccess", "MakeOrCheckAccess"));
            makeOrCheck.checked = false;
        }
    }

    function validateCreateAccess(sender) {

        ctrl = sender;
        var createCheck = document.getElementById(ctrl.id);
        if (createCheck.checked == true) {  // if create access is checked, check view access too.
            var viewCheck = document.getElementById(ctrl.id.replace("CreateAccess", "ViewAccess"));
            viewCheck.checked = true;
            var editCheck = document.getElementById(ctrl.id.replace("CreateAccess", "EditAccess"));
            editCheck.checked = true;
            var verifyCheck = document.getElementById(ctrl.id.replace("CreateAccess", "VerifyAccess"));
            verifyCheck.checked = false;
            var makeOrCheck = document.getElementById(ctrl.id.replace("CreateAccess", "MakeOrCheckAccess"));
            makeOrCheck.checked = true;

        }
    }

    function validateEditAccess(sender) {

        ctrl = sender;
        var editCheck = document.getElementById(ctrl.id);

        if (editCheck.checked == true) {  // if edit access is checked, check view
            var viewCheck = document.getElementById(ctrl.id.replace("EditAccess", "ViewAccess"));
            viewCheck.checked = true;
            var verifyCheck = document.getElementById(ctrl.id.replace("EditAccess", "VerifyAccess"));
            verifyCheck.checked = false;
            var makeOrCheck = document.getElementById(ctrl.id.replace("EditAccess", "MakeOrCheckAccess"));
            makeOrCheck.checked = true;
        }
    }

    function validateDeleteAccess(sender) {

        ctrl = sender;
        var deleteCheck = document.getElementById(ctrl.id);
        if (deleteCheck.checked == true) {  // if delete access is checked, check view.
            var viewCheck = document.getElementById(ctrl.id.replace("DeleteAccess", "ViewAccess"));
            viewCheck.checked = true;
            var verifyCheck = document.getElementById(ctrl.id.replace("DeleteAccess", "VerifyAccess"));
            verifyCheck.checked = false;
            var makeOrCheck = document.getElementById(ctrl.id.replace("DeleteAccess", "MakeOrCheckAccess"));
            makeOrCheck.checked = true;
        }
    }

    </script>

}

PermissionManagement.Web/Views/UserSetup/ListRole.cshtml
@using PermissionManagement.Utility;
@model IEnumerable<PermissionManagement.Model.Role>

@{
    ViewBag.Title = "List Role";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section MainContent {
<div class="row">
	<div class="col-md-12 col-xs-12 col-sm-12 align-text-bottom page-head-line">
		List Role |
		@{var status = Access.IsAccessRightInRoleProfile(Constants.Modules.UserSetup, Constants.AccessRights.Create);
			if (status)
			{
				<a href="@Url.Action("CreateRole", "UserSetup")" class="btn btn-link btn-sm text-capitalize">
					<i class="fa fa-plus" aria-hidden="true"></i>
					Create New Role
				</a>
				@*@Html.ActionLink("Create New", "CreateUser")*@
			}
		}

		<div class="pull-right" style="font-size:12px;">
			@using (@Html.BeginForm("ExportExcel", "UserSetup", FormMethod.Post, new { @class = "save_as_excel" }))
			{
				@*<button class="btn btn-default pull-right tooltipBottomLeft" tooltip="Export to Excel" type="submit"  onclick="return GetData();" id="ExportExcel">
					<span class="glyphicon glyphicon-save "></span> <span class="fa fa-file-excel-o"></span>
				</button>*@
				<button class="btn btn-link btn-sm tooltipBottomLeft" type="submit" name="ExportExcel" tooltip="Export to Excel" onclick="return GetData();" id="ExportExcel"> <span class="glyphicon glyphicon-save"></span> Save as Excel</button>
				@Html.Hidden("searchKey")
			}
			|
			<button type="button" class="btn btn-link btn-sm refresh-button" id="refresh-button">
				<span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Refresh
			</button>
		</div>

	</div>
</div>

<div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table id="RoleListTbl" class="table table-bordered table-striped table-hover display" cellspacing="0" >
                    <thead>
                        <tr>
                            <th>
                                Edit
                            </th>
                            <th>
                                Delete
                            </th>
                            <th>
                                Role Name
                            </th>
                            <th>
                                Role Description
                            </th>
                        </tr>
                    </thead>
                    @{var status2 = Access.IsAccessRightInRoleProfile(Constants.Modules.UserSetup, Constants.AccessRights.Edit); }
                    @{var status3 = Access.IsAccessRightInRoleProfile(Constants.Modules.UserSetup, Constants.AccessRights.Delete); }
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.ActionLink(status2 ? "Edit" : "View", "EditRole", new { id = item.RoleId },new {@class="btn btn-link" })
                            </td>
                            <td >
                                @if (status3)
                                {
                                    
                                    <a href="@Html.GetPostUrl("UserSetup/DeleteRole", item.RoleId.ToString())" class="btn btn-link">
                                       Delete
                                    </a>                                    
                                    @Html.Hidden("RoleId", item.RoleId.ToString())                                
                                }
                                else
                                {
                                    @Html.Raw("Delete")
                                }
                            </td>
                            <td style="vertical-align:middle;">
                                @item.RoleName
                            </td>
                            <td style="vertical-align:middle;">
                                @item.Description
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
}
@section scripts {
    <script type="text/javascript">
        $(document).ready(function ()
        {
            $('#RoleListTbl').dataTable();
        });
        function GetData()
        {
            document.getElementById("searchKey").value = $('input[type="search"]').val(); return true;
        }
    </script>
}

PermissionManagement.Web/Views/UserSetup/ModuleAccessEditor.cshtml
@using PermissionManagement.Utility;
@model PermissionManagement.Model.RoleModuleAccess

<tr>
    @{var prefx = @ViewData["prefix"] + ".index";}
    <input type="hidden" name="@prefx" value="@ViewData.Model.ModuleId" />
    @{var fieldPrefix = string.Format("{0}[{1}].", ViewData["prefix"], ViewData.Model.ModuleId); }
    @Html.Hidden(fieldPrefix + "ModuleId", ViewData.Model.ModuleId)
    @Html.Hidden(fieldPrefix + "ModuleName", ViewData.Model.ModuleName)
    <td>@Html.DisplayFor(model => model.ModuleName)</td>
    <td>@Html.CheckBox(fieldPrefix + "ViewAccess", ViewData.Model.ViewAccess.HasValue ? ViewData.Model.ViewAccess.Value : false, new { onclick = "return validateViewAccess(this);" })</td>
    <td>@Html.CheckBox(fieldPrefix + "VerifyAccess", ViewData.Model.VerifyAccess.HasValue ? ViewData.Model.VerifyAccess.Value : false, new { onclick = "return validateVerifyAccess(this);" })</td>
    <td>@Html.CheckBox(fieldPrefix + "MakeOrCheckAccess", ViewData.Model.MakeOrCheckAccess.HasValue ? ViewData.Model.MakeOrCheckAccess.Value : false, new { onclick = "return validateMakeOrCheckAccess(this);" })</td>
    <td>@Html.CheckBox(fieldPrefix + "CreateAccess", ViewData.Model.CreateAccess.HasValue ? ViewData.Model.CreateAccess.Value : false, new { onclick = "return validateCreateAccess(this);" })</td>
    <td>@Html.CheckBox(fieldPrefix + "EditAccess", ViewData.Model.EditAccess.HasValue ? ViewData.Model.EditAccess.Value : false, new { onclick = "return validateEditAccess(this);" })</td>
    <td>@Html.CheckBox(fieldPrefix + "DeleteAccess", ViewData.Model.DeleteAccess.HasValue ? ViewData.Model.DeleteAccess.Value : false, new { onclick = "return validateDeleteAccess(this);" })</td>
</tr>