PermissionManagement.Web/Controllers/PortalSettingsController.cs
using PermissionManagement.Model;
using PermissionManagement.Services;
using PermissionManagement.Utility;
using PermissionManagement.Validation;
using PermissionManagement.Web;
using System.Web.Mvc;

namespace PermissionManagement.Controllers
{
    public class PortalSettingsController : BaseController
    {
        #region Properties and Variables
        private IPortalSettingsService portalSettingsServiceInstance;
        PortalSettings portalSettings = new PortalSettings();
        PortalSetting portalSetting = new PortalSetting();
        ValidationStateDictionary validationStateDict = new ValidationStateDictionary();

        public PortalSettingsController(IPortalSettingsService portalSettingsService)
        { 
            portalSettingsServiceInstance = portalSettingsService; 
        }

        #endregion

        #region Portal Settings Action Results
        #region View Settings List
        [AuditFilter(AuditLogLevel.LevelFive)]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.View)]
        public ActionResult ViewSettingsList()
        {
            portalSettings.settings = portalSettingsServiceInstance.GetPortalSettings();
            return View(portalSettings.settings);
        }

        [CompressFilter]
        [HttpPost]
        [ActionName("PortalSettingsListExcelDownload")]
        [AuditFilter(AuditLogLevel.LevelFive)]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.View)]
        public void PortalSettingsListExcelDownload()
        {
            portalSettings.settings = portalSettingsServiceInstance.GetPortalSettings();
            new Export().ToFile(portalSettings.settings, Response,"PortalSettings_Report");
        }

        [CompressFilter]
        [HttpPost]
        [ActionName("PortalSettingsListWordDownload")]
        [AuditFilter(AuditLogLevel.LevelFive)]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.View)]
        public void PortalSettingsListWordDownload()
        {
            portalSettings.settings = portalSettingsServiceInstance.GetPortalSettings();
            new Export().ToFile(portalSettings.settings, Response, "PortalSettings_Report",EXPORTTYPE.WORD);
        }

        #endregion

        #region Add Settings
        [AuditFilter(AuditLogLevel.LevelFive)]
        [HttpGet]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.View)]
        public ActionResult AddSettings() { return View(); }

        [AuditFilter()]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.Edit)]
        public ActionResult AddSettings(PortalSetting portalSetting)
        {
            ViewBag.status = portalSettingsServiceInstance.AddPortalSetting(portalSetting, ref validationStateDict);
            return View();
        }
        #endregion

        #region Edit Settings
        [AuditFilter(AuditLogLevel.LevelFive)]
        [HttpGet]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.View)]
        public ActionResult EditSettings(int PSID, string key)
        {
            portalSetting = portalSettingsServiceInstance.GetSettingByKey(key);
            return View(portalSetting);
        }

        [AuditFilter(AuditLogLevel.LevelZero)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SecurityAccess(Constants.Modules.UserSetup, Constants.AccessRights.Edit)]
        public ActionResult EditSettings(PortalSetting portalSetting)
        {
            ViewBag.status = portalSettingsServiceInstance.UpdateSetting(portalSetting);
            return View();
        }
        #endregion

        #endregion
    }
}

PermissionManagement.Web/Views/PortalSettings/AddSettings.cshtml
@model PermissionManagement.Model.PortalSetting

@{
    ViewBag.Title = "Add Portal Setting";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section MainContent {
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive page-head-line">
                <div class="col-md-9 align-text-bottom">
                    <br />Portal Setting
                </div>
            </div>
        </div>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="form-horizontal  col-md-12 col-sm-8 col-xs-12 col-xs-offset-0">
                <p>     @Html.ActionLink("Back to List", "ViewSettingsList")</p>
                <hr />
                @{if (!string.IsNullOrEmpty(@ViewBag.status))
                {
                    <div class="alert alert-success fade in" id="idalert">
                        <strong> @ViewBag.status</strong>
                    </div>
                }}
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Key, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control input-sm" } })
                            @Html.ValidationMessageFor(model => model.Key)
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Value, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control input-sm" } })
                            @Html.ValidationMessageFor(model => model.Value)
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    &nbsp;
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <input type="submit" value="Add Key Value Pair" class="form-control btn-primary" />
                </div>
            </div>
        </div>
        <hr />
        <p>     @Html.ActionLink("Back to List", "ViewSettingsList")</p>
    }
}

PermissionManagement.Web/Views/PortalSettings/EditSettings.cshtml
@model PermissionManagement.Model.PortalSetting

@{
    ViewBag.Title = "Edit Setting";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section MainContent {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="form-horizontal  col-md-12 col-sm-8 col-xs-12 col-xs-offset-0">
                <h1 class="page-head-line">Portal Setting</h1>
                <p>     @Html.ActionLink("Back to List", "ViewSettingsList")</p>
                <hr />
                @{if (!string.IsNullOrEmpty(@ViewBag.status))
                {
                    <div class="alert alert-success fade in" id="idalert">
                        <strong> @ViewBag.status</strong>
                    </div>
                }}
            </div>
            <div class="ro">
                <div class="form-group">
                    @Html.LabelFor(model => model.Key, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control input-sm", @readonly = true } })
                        @Html.ValidationMessageFor(model => model.Key)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Value, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control input-sm" } })
                        @Html.ValidationMessageFor(model => model.Value)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        &nbsp;
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="form-control btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
         <hr />
        <p>     @Html.ActionLink("Back to List", "ViewSettingsList")</p>
    }
}

<div class="form-horizontal">
    <h4>PortalSetting</h4>
    <hr />
    @Html.ValidationSummary(true)


</div>

PermissionManagement.Web/Views/PortalSettings/ViewSettingsList.cshtml
@model IEnumerable<PermissionManagement.Model.PortalSetting>

@{
    ViewBag.Title = "List Portal Settings";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section MainContent {

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <div class="table-responsive page-head-line">
        <div class="col-md-9 align-text-bottom ">
            <br /> Portal Setting
        </div>
        <div class="col-md-3 align">
            @using (Html.BeginForm("PortalSettingsListExcelDownload", "PortalSettings", FormMethod.Post))
            {
                @*<button class="btn btn-default pull-right tooltips" type="submit" name="ExportExcel" glose="Export to Excel" onclick="return GetData();" id="ExportExcel"> <span class="glyphicon glyphicon-save "></span> Save as Excel</button>*@
                <button class="btn btn-default pull-right tooltipBottomLeft" type="submit" name="ExportExcel" tooltip="Export to Excel" onclick="return GetData();" id="ExportExcel"><span class="fa fa-arrow-down">&nbsp;</span><span class="fa fa-file-excel-o"></span></button>
            }
            @*@using (Html.BeginForm("PortalSettingsListWordDownload", "PortalSettings", FormMethod.Post))
            {
                <button class="btn btn-default pull-right tooltipBottomLeft" type="submit" name="ExportWord" tooltip="Export to Word" onclick="return GetData();" id="ExportWord"><span class="fa fa-arrow-down">&nbsp;</span><span class="fa fa-file-word-o"></span></button>
            }*@
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <p>
                @Html.ActionLink("Add Setting", "AddSettings")
            </p>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover display" cellspacing="0">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Key)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Value)
                            </th>
                            <th>Edit</th>
                            @*<th>Delete</th>*@
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Key)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Value)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "EditSettings", new { item.PSID, item.Key })
                                </td>
                                @*   <td>
                                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                                    </td>*@
                            </tr>
                        }
                    </table>
                </div>
            }
        </div>
    </div>
    <hr />
    <p>
        @Html.ActionLink("Add Setting", "AddSettings")
    </p>

}