PermissionManagement.Web/Controllers/RemitlyPayoutController.cs
using PermissionManagement.Model;
using PermissionManagement.Repository;
using PermissionManagement.Repository.Interface;
using PermissionManagement.Services;
using PermissionManagement.Utility;
using PermissionManagement.Validation;
using System;
using System.Configuration;
using System.Net.Http;
using System.Web.Mvc;


namespace PermissionManagement.Web
{
    public class RemitlyPayoutController : BaseController
    {
        #region Properties and Variables
        private ISecurityService _securityService;
        private ICacheService _cacheService;
        private IFinacleRepository _flexCubeRepository;
        private ICashPickup _cashPickupService;
        #endregion

        public RemitlyPayoutController(ISecurityService securityService, ICacheService cacheService, IFinacleRepository finacleRepository, ICashPickup cashPickupService)
        {
            _securityService = securityService;
            _flexCubeRepository = finacleRepository;
            _cacheService = cacheService;
            _cashPickupService = cashPickupService;
        }


        [AuditFilter(AuditLogLevel.LevelThree)]
        [SecurityAccess(Constants.Modules.RemitlyPayout, Constants.AccessRights.View)]
        public ActionResult Index()
        {
            //List cash pickup for the branch...
            var cashPickup = _cashPickupService.ListCashPickup();

            return View(cashPickup);
        }

        [HttpGet]
        public ActionResult RetrieveReference()
        {
            return View();
        }

        [AuditFilter(AuditLogLevel.LevelThree)]
        [SecurityAccess(Constants.Modules.RemitlyPayout, Constants.AccessRights.View)]
        public ActionResult RetrieveReference(string referenceNumber)
        {
            //form display input for branch teller to enter reference number presented by customer
            if (referenceNumber == null)
            {
                throw new Exception("Cannot get details for requested reference Number");
            }

            //call RemmitlyAPI to get the details
            var refRetrieve = _cashPickupService.RetrieveReference(referenceNumber);
            return View(refRetrieve);

            //if successful, write to db and redirect page to display the details

            //if not display the appropriate error

            //return View();
        }

        [AuditFilter(AuditLogLevel.LevelThree)]
        [SecurityAccess(Constants.Modules.RemitlyPayout, Constants.AccessRights.View)]
        public ActionResult EditRemitlyCashPayout(string referenceNumber)
        {
            //the form to display the details of retrieved reference number (its a get)
            var EditedCashPayOut = _cashPickupService.EditRemittance(referenceNumber);
            return View(EditedCashPayOut);
        }

        [AuditFilter(AuditLogLevel.LevelOne)]
        [SecurityAccess(Constants.Modules.RemitlyPayout, new string[] { Constants.AccessRights.Create, Constants.AccessRights.Edit })]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditRemitlyCashPayout(RemittanceCashPickup model)
        {
            //the form to to process thre retrieved reference number
            using (var client = new HttpClient())
            {
                string url = ConfigurationManager.AppSettings["RemitlyBaseURL"];

                var content = new MultipartFormDataContent();
                client.BaseAddress = new Uri(url);
                var responseTask = client.PostAsync($"/IMTOAPI.Project/Remitly/UpdateTransfer/", content);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    TempData["SuccessMessage"] = $"Cash Pickup was successfully updated.";

                    return RedirectToAction("Index", new { CashPickupIdId = model.Id });
                }

                if ((int)result.StatusCode == 422)
                {
                    ModelState.AddModelError("", "CashPickup entry Already Exists!");
                }
                else
                {
                    ModelState.AddModelError("", "Some kind of error. CashPickup not updated!");
                }
            }

            var cashPicks = _cashPickupService.EditRemittance(model.ReferenceNumber);
            return View(cashPicks);
            //here teller accept and record customer identity.
            //system validate and send for approval

            //return View();
        }

        [AuditFilter(AuditLogLevel.LevelOne)]
        [SecurityAccess(Constants.Modules.RemitlyPayout, new string[] { Constants.AccessRights.Verify, Constants.AccessRights.MakeOrCheck })]
        public ActionResult ApproveRemitlyCashPayout(string referenceNumber)
        {
            //the form for approval personel to view and take action on approval or reject or reject for correction
            var CashPickupToApproved = _cashPickupService.RetrieveReference(referenceNumber);
            if (referenceNumber == null)
            {
                return HttpNotFound();
            }
            return View(CashPickupToApproved);
        }

        [AuditFilter()]
        [SecurityAccess(Constants.Modules.RemitlyPayout, new string[] { Constants.AccessRights.Verify, Constants.AccessRights.MakeOrCheck })]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [MultipleButton(Name = "action", Argument = "RejectForCorrectionRemitlyCashPayout")]
        public ActionResult RejectForCorrectionRemitlyCashPayout(RemittanceCashPickup model)
        {
            return ExecuteAction(model, Constants.ApprovalStatus.RejectedForCorrection);
        }

        [AuditFilter()]
        [SecurityAccess(Constants.Modules.RemitlyPayout, new string[] { Constants.AccessRights.Verify, Constants.AccessRights.MakeOrCheck })]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [MultipleButton(Name = "action", Argument = "RejectRemitlyCashPayout")]
        public ActionResult RejectRemitlyCashPayout(RemittanceCashPickup model)
        {
            return ExecuteAction(model, Constants.ApprovalStatus.Rejected);
        }

        [AuditFilter()]
        [SecurityAccess(Constants.Modules.RemitlyPayout, new string[] { Constants.AccessRights.Verify, Constants.AccessRights.MakeOrCheck })]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [MultipleButton(Name = "action", Argument = "ApproveRemitlyCashPayout")]
        public ActionResult ApproveRemitlyCashPayout(RemittanceCashPickup model)
        {
            return ExecuteAction(model, Constants.ApprovalStatus.Approved);
        }

        private ActionResult ExecuteAction(RemittanceCashPickup model, string approvalStatus)
        {
            ValidationStateDictionary states = new ValidationStateDictionary();

            var models = _cashPickupService.RetrieveReference(model.ReferenceNumber);
            var dbApprovalStatus = Constants.ApprovalStatus.Pending;

            //the user that put a record in pending mode will always be stored as initiated by - meaning the db will be updated.
            var permitEdit = Access.CanEdit(Constants.Modules.RemitlyPayout, model.InitiatedBy, dbApprovalStatus, model.IsDeleted);
            if (permitEdit)
            {
                model.ApprovedStatus = approvalStatus;

                var updated = _cashPickupService.EditRemittance(model.ReferenceNumber);
                if (!states.IsValid)
                {
                    model.UserRole = new Role() { RoleId = model.RoleId };
                    ModelState.AddModelErrors(states);
                    var errorList = ValidationHelper.BuildModelErrorList(states);
                    SetAuditInfo(Helper.StripHtml(errorList, true), string.Empty);
                    return View(model);
                }
                else
                {
                    if (updated == null) { Warning(Constants.Messages.ConcurrencyError, true); }
                    else { Success(Constants.Messages.SaveSuccessful, true); }
                    return RedirectToAction("Index");
                }
            }
            else
            {
                Warning(Constants.Messages.EditNotPermittedError, true);
                return RedirectToAction("Index");
            }
        }
    }
}

PermissionManagement.Web/Views/RemitlyPayout/EditRemitlyCashPayout.cshtml
@model PermissionManagement.Model.RemitlyTransferHeader

@{
    ViewBag.Title = "EditRemitlyCashPayout";
}

<h2>EditRemitlyCashPayout</h2>

@using (Html.BeginForm("EditRemitlyCashPayout", "RemitlyPayout"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Reference_Number, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Reference_Number, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Reference_Number, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Created_On, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Created_On, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Created_On, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Payer_Codes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Payer_Codes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Payer_Codes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Update CashPickup" class="btn btn-default" />
        </div>
    </div>
</div>
}


@if (ViewBag.Result == "Success")
{
    <h2>Update transfer</h2>
    <table class="tabel table-sm table-striped table-bordered m-2">
        <thead>
            <tr>
                <th>Reference Number</th>
                <th>Created On</th>
                <th>Payer Code</th>
                <th>State</th>
                <th>Type </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Reference_Number</td>
                <td>@Model.Created_On</td>
                <td>@Model.Payer_Codes</td>
                <td>@Model.State</td>
                <td>@Model.Type</td>
            </tr>
        </tbody>

    </table>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PermissionManagement.Web/Views/RemitlyPayout/Index.cshtml
@model IEnumerable<PermissionManagement.Model.RemitlyTransferHeader>

@{
    ViewBag.Title = "Index";
}

<h2>List of Cash PickUp</h2>

<p>
    @Html.ActionLink("RetrieveReference", "RemitlyPayout", "Fetch Transfer Details", null, new {@class="btn btn-sm btn-secondary"})
</p>

<table class="table table-sm table-striped" table-bordered m-2>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Reference_Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created_On)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th></th>
        </tr>
    </thead>

@foreach (var item in Model) {
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Reference_Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created_On)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
        </tr>
    </tbody>
}
</table>

PermissionManagement.Web/Views/RemitlyPayout/RetrieveReference.cshtml
@model PermissionManagement.Model.RemitlyRemittance
@{
    ViewBag.Title = "RetrieveReference";
}

<h2>Enter ReferenceCode to generate transfer</h2>
@using (Html.BeginForm("RetrieveReference", "RemitlyPayout"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "Please fix this error")
    <div class="form-group">
        @Html.LabelFor(m => m.Reference_Number)
        @Html.TextBoxFor(m => m.Reference_Number, new { @class = "form-controll" })
        @Html.ValidationMessageFor(m => m.Reference_Number)
    </div>

    <div class="text-center panel-body">
        <button type="submit" class="btn btn-sm btn-primary"> Get Transfer</button>
    </div>
}

@if (Model != null)
{
    <h2> Detail Transfer</h2>
    <table class="table table-sm table-striped" table-bordered m-2>
        <thead>
            <tr>
                <th>Reference Number</th>
                <th>Created On</th>
                <th>State</th>
                <th>Type</th>
                <th>Payer Code</th>
                <th>Send Amount</th>
                <th>Receive Amount</th>
                <th>Bank Account</th>
                <th>Sender</th>
                <th>Reciever</th>
                <th>Name</th>
                <th>Address</th>
                <th>Identification</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Reference_Number</td>
                <td>@Model.Created_On</td>
                <td>@Model.State</td>
                <td>@Model.Type</td>
                <td>@Model.Payer_Codes</td>
                <td>@Model.Send_Amount</td>
                <td>@Model.Receive_Amount</td>
                <td>@Model.Bank_Account</td>
                <td>@Model.Sender</td>
                <td>@Model.Receiver</td>
                <td>@Model.Name</td>
                <td>@Model.Address</td>
                <td>@Model.Identification</td>

            </tr>
        </tbody>
    </table>

}